package com.dougretrogames.gamepadfixer.model

/**
 * Represents a complete .kl (KeyLayout) file.
 *
 * @property device   The gamepad this file belongs to
 * @property mappings Ordered list of key/axis mappings
 * @property content  Raw text content of the file (used when loaded from disk)
 */
data class KlFile(
    val device: GamepadDevice,
    val mappings: List<KeyMapping> = emptyList(),
    val content: String = ""
) {
    /** The suggested installation path on a rooted device */
    val systemPath: String
        get() = "/system/usr/keylayout/${device.klFileName}"

    /**
     * Generates the full .kl file text from the mappings list.
     * Falls back to [content] when mappings list is empty.
     */
    fun generateContent(): String {
        if (mappings.isEmpty()) return content
        val sb = StringBuilder()
        sb.appendLine("# Generated by Android Gamepad KL Fixer")
        sb.appendLine("# Device : ${device.name}")
        sb.appendLine("# VID    : 0x${device.vendorHex}")
        sb.appendLine("# PID    : 0x${device.productHex}")
        sb.appendLine()
        mappings.forEach { sb.appendLine(it.toKlLine()) }
        return sb.toString()
    }
}
