package com.dougretrogames.gamepadfixer.model

/**
 * Represents a complete .kl key layout file with its mappings.
 */
data class KlFile(
    val fileName: String,
    val vendorId: Int,
    val productId: Int,
    val mappings: MutableList<KlMapping> = mutableListOf()
) {
    /**
     * Generates the full text content of the .kl file.
     */
    fun toFileContent(): String {
        val sb = StringBuilder()
        sb.appendLine("# Key layout file generated by Android Gamepad KL Fixer")
        sb.appendLine("# Vendor: %04x  Product: %04x".format(vendorId, productId))
        sb.appendLine("# Generated: ${java.util.Date()}")
        sb.appendLine()
        val keys = mappings.filterIsInstance<KlMapping.KeyMapping>()
        val axes = mappings.filterIsInstance<KlMapping.AxisMapping>()
        if (keys.isNotEmpty()) {
            sb.appendLine("# Key mappings")
            keys.forEach { sb.appendLine(it.toKlLine()) }
            sb.appendLine()
        }
        if (axes.isNotEmpty()) {
            sb.appendLine("# Axis mappings")
            axes.forEach { sb.appendLine(it.toKlLine()) }
        }
        return sb.toString()
    }

    companion object {
        /**
         * Android system path where .kl files are stored (requires root).
         */
        const val SYSTEM_KL_PATH = "/system/usr/keylayout/"
    }
}
