package com.dougretrogames.gamepadklfixer.kl

import android.view.KeyEvent
import android.view.MotionEvent
import com.dougretrogames.gamepadklfixer.model.GamepadDevice
import com.dougretrogames.gamepadklfixer.model.KeyEventRecord

/**
 * Generates .kl (KeyLayout) file content for a given gamepad device.
 *
 * The KeyLayout file format is a plain-text file used by Android's input system
 * to map scan codes to key codes. Files are placed at:
 *   /system/usr/keylayout/Vendor_XXXX_Product_XXXX.kl
 *
 * Reference: https://source.android.com/docs/core/interaction/input/key-layout-files
 */
object KlFileGenerator {

    /**
     * Default standard gamepad key mapping (scan code -> Android key name).
     * These represent typical USB HID report IDs for a standard gamepad.
     */
    private val DEFAULT_KEY_MAPPINGS: List<Pair<Int, String>> = listOf(
        // Face buttons (typical Xbox/PlayStation mapping)
        0x130 to "BUTTON_A",
        0x131 to "BUTTON_B",
        0x132 to "BUTTON_C",
        0x133 to "BUTTON_X",
        0x134 to "BUTTON_Y",
        0x135 to "BUTTON_Z",
        0x136 to "BUTTON_L1",
        0x137 to "BUTTON_R1",
        0x138 to "BUTTON_L2",
        0x139 to "BUTTON_R2",
        0x13a to "BUTTON_SELECT",
        0x13b to "BUTTON_START",
        0x13c to "BUTTON_MODE",
        0x13d to "BUTTON_THUMBL",
        0x13e to "BUTTON_THUMBR"
    )

    /**
     * Default axis mappings for a standard gamepad.
     */
    private val DEFAULT_AXIS_MAPPINGS: List<Triple<String, String, String>> = listOf(
        Triple("ABS_X", "X", ""),
        Triple("ABS_Y", "Y", ""),
        Triple("ABS_Z", "Z", ""),
        Triple("ABS_RZ", "RZ", ""),
        Triple("ABS_HAT0X", "HAT_X", ""),
        Triple("ABS_HAT0Y", "HAT_Y", ""),
        Triple("ABS_BRAKE", "LTRIGGER", ""),
        Triple("ABS_GAS", "RTRIGGER", "")
    )

    /**
     * Generates KL file content using default standard mappings.
     *
     * @param device The gamepad device to generate for
     * @return String content of the .kl file
     */
    fun generateDefault(device: GamepadDevice): String {
        return buildKlContent(
            device = device,
            keyMappings = DEFAULT_KEY_MAPPINGS,
            axisMappings = DEFAULT_AXIS_MAPPINGS,
            capturedKeys = emptyList()
        )
    }

    /**
     * Generates KL file content from captured key events during the test session.
     * Merges captured keys with defaults for any missing mappings.
     *
     * @param device       The gamepad device
     * @param capturedKeys List of KeyEventRecord from live capture session
     * @return String content of the .kl file
     */
    fun generateFromCapture(device: GamepadDevice, capturedKeys: List<KeyEventRecord>): String {
        return buildKlContent(
            device = device,
            keyMappings = DEFAULT_KEY_MAPPINGS,
            axisMappings = DEFAULT_AXIS_MAPPINGS,
            capturedKeys = capturedKeys
        )
    }

    private fun buildKlContent(
        device: GamepadDevice,
        keyMappings: List<Pair<Int, String>>,
        axisMappings: List<Triple<String, String, String>>,
        capturedKeys: List<KeyEventRecord>
    ): String {
        val sb = StringBuilder()

        sb.appendLine("# KeyLayout file generated by GamepadKLFixer")
        sb.appendLine("# Device: ${device.name}")
        sb.appendLine("# Vendor ID : ${device.vendorHex} (${device.vendorId})")
        sb.appendLine("# Product ID: ${device.productHex} (${device.productId})")
        sb.appendLine("# Generated : ${java.text.SimpleDateFormat("yyyy-MM-dd HH:mm:ss", java.util.Locale.US).format(java.util.Date())}")
        sb.appendLine("# Reference : https://source.android.com/docs/core/interaction/input/key-layout-files")
        sb.appendLine()

        sb.appendLine("# ----- Key Mappings -----")
        // Add captured keys first (with WAKE flag if they are common game buttons)
        val capturedScanCodes = mutableSetOf<Int>()
        for (record in capturedKeys.filter { it.action == android.view.KeyEvent.ACTION_DOWN }.distinctBy { it.scanCode }) {
            if (record.scanCode > 0) {
                val keyName = KeyEvent.keyCodeToString(record.keyCode).removePrefix("KEYCODE_")
                sb.appendLine("key ${record.scanCode}   $keyName   WAKE")
                capturedScanCodes.add(record.scanCode)
            }
        }

        // Add defaults for any scan codes not captured
        for ((scanCode, keyName) in keyMappings) {
            if (scanCode !in capturedScanCodes) {
                sb.appendLine("key $scanCode   $keyName   WAKE")
            }
        }
        sb.appendLine()

        sb.appendLine("# ----- Axis Mappings -----")
        for ((absAxis, motionAxis, _) in axisMappings) {
            sb.appendLine("axis $absAxis   $motionAxis")
        }

        return sb.toString()
    }

    /**
     * Returns the axis name string for a MotionEvent axis integer constant.
     */
    fun axisName(axis: Int): String = MotionEvent.axisToString(axis)

    /**
     * Validates that the KL content has at least one key or axis mapping.
     */
    fun validate(content: String): Boolean {
        return content.lines().any { line ->
            val trimmed = line.trim()
            !trimmed.startsWith("#") && (trimmed.startsWith("key ") || trimmed.startsWith("axis "))
        }
    }
}
