name: Android CI/CD

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: 8.14.5

      - name: Decode Keystore
        id: decode_keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > release.jks
          echo "keystore_path=$(pwd)/release.jks" >> $GITHUB_ENV

      - name: Build Release APK
        run: |
          unset JAVA_TOOL_OPTIONS
          unset GRADLE_OPTS
          gradle assembleRelease --stacktrace
        env:
          KEYSTORE_FILE: ${{ env.keystore_path }}
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

      - name: Rename APK
        run: |
          cp app/build/outputs/apk/release/app-release.apk GamepadKLFixer-Release.apk

      - name: Definir nome do artefato
        id: vars
        run: echo "artifact_name=GamepadKLFixer-Release-${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.vars.outputs.artifact_name }}
          path: GamepadKLFixer-Release.apk
