name: Android CI/CD

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: 8.14.5

      - name: Grant execute permission to gradlew
        run: chmod +x gradlew

      - name: Decode Keystore
        id: decode_keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > release.jks
          echo "keystore_path=$(pwd)/release.jks" >> $GITHUB_ENV

      - name: Build Release APK
        run: |
          unset JAVA_TOOL_OPTIONS
          unset GRADLE_OPTS
          ./gradlew assembleRelease --stacktrace
        env:
          KEYSTORE_FILE: ${{ env.keystore_path }}
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: app/build/outputs/apk/release/*.apk
